---
label: service
hide_body: false
fields:
- name: title
  type: text
  config:
    required: false
  label: Title
- name: filter
  type: text
  config:
    required: false
  label: Filter
- name: main_image
  type: file
  config:
    maxSize: 250
  label: Main image
- name: number_of_shipments
  type: number
  label: Number of shipments
  description: ''
  default: 0
  required: true
  config:
    min: 
    max: 
    step: 
- name: steps
  type: field_group_list
  fields:
  - name: title
    type: text
    config:
      required: false
    label: title
    default: Step
  - name: number
    type: text
    config:
      required: false
    label: Number
  - name: image
    type: file
    config:
      maxSize: 250
    label: Image
    default: "/uploads/step_dummy.jpg"
  - name: description
    type: textarea
    default: Lorem Khaled Ipsum is a major key to success. Eliptical talk. You should
      never complain, complaining is a weak emotion, you got life, we breathing, we
      blessed. Cloth talk. Celebrate success right, the only way, apple. Find peace,
      life is like a water fall, you’ve gotta flow. Look at the sunset, life is amazing,
      life is beautiful, life is what you make it. Stay focused. Let me be clear,
      you have to make it through the jungle to make it to paradise, that’s the key,
      Lion! The other day the grass was brown, now it’s green because I ain’t give
      up.
    config:
      required: false
      wysiwyg: false
      schema:
        format: markdown
    label: Description
  config:
    min: 
    max: 
    labelField: 
  label: Steps
pages:
- _services/freight.md
- _services/logistics.md
